eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
      #defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
        instanceId: ${spring.application.name}:${random.value}

jwt:
  secret-key: secretkey123456789